title: Automations
id: automations
path: automations
icon: mdi:home-variant
visible:
  - user: 2e93f54c62e549c8aeperson2748de6bed9d
cards:
- type: entities
  title: Room status
  show_header_toggle: false
  entities:
  - entity: automation.living_room_occupied
    secondary_info: last-triggered
  - entity: automation.living_room_not_occupied
    secondary_info: last-triggered
  - type: divider
  - entity: automation.living_room_mode_motion
    secondary_info: last-triggered
  - entity: automation.living_room_mode_motion_off
    secondary_info: last-triggered
  - type: divider
  - entity: automation.living_room_arrival
    secondary_info: last-triggered
  - entity: automation.living_room_away
    secondary_info: last-triggered
  - entity: automation.living_room_bedtime
    secondary_info: last-triggered
  - entity: automation.living_room_day_on
    secondary_info: last-triggered
  - entity: automation.living_room_dim
    secondary_info: last-triggered
  - entity: automation.living_room_dim_off
    secondary_info: last-triggered
  - entity: automation.living_room_night_on
    secondary_info: last-triggered
  - entity: automation.living_room_off
    secondary_info: last-triggered
  - entity: automation.living_room_off_empty
    secondary_info: last-triggered
  - entity: automation.living_room_override
    secondary_info: last-triggered
  - type: divider
  - entity: automation.living_room_movement
    secondary_info: last-triggered
  - type: divider
  - entity: automation.cooler_outside_livingroom
    secondary_info: last-triggered
  - entity: automation.hotter_outside_livingroom
    secondary_info: last-triggered
- type: entities
  title: Automations for the living room lights
  show_header_toggle: false
  entities:
  - entity: automation.living_room_lights_bedtime
    secondary_info: last-triggered
  - entity: automation.living_room_lights_day_on
    secondary_info: last-triggered
  - entity: automation.living_room_lights_dim_on
    secondary_info: last-triggered
  - entity: automation.living_room_lights_motion
    secondary_info: last-triggered
  - entity: automation.living_room_lights_night_on
    secondary_info: last-triggered
  - entity: automation.living_room_lights_off
    secondary_info: last-triggered
  - type: divider
  - entity: automation.tv_light_on
    secondary_info: last-triggered
  - entity: automation.living_room_dark_motion
    secondary_info: last-triggered
  - entity: automation.living_room_dark_no_motion
    secondary_info: last-triggered
  - type: divider
  - entity: automation.living_room_table_light_unavailable_on
    secondary_info: last-triggered
  - entity: automation.living_room_table_light_unavailable_off
    secondary_info: last-triggered
- type: entities
  title: Living room media automations
  show_header_toggle: false
  entities:
  - entity: automation.all_away_media_off
    secondary_info: last-triggered
  - entity: automation.tv_on_sonos_off
    secondary_info: last-triggered
  - entity: automation.sonos_on_tv_mute
    secondary_info: last-triggered
  - entity: automation.sonos_off_tv_unmute
    secondary_info: last-triggered
- type: entities
  title: Remote automations
  show_header_toggle: false
  entities:
  - entity: automation.dimmer
    secondary_info: last-triggered
  - entity: automation.dimmer_on
    secondary_info: last-triggered
  - entity: automation.dimmer_off
    secondary_info: last-triggered
  - entity: automation.dimmer_on_while_away
    secondary_info: last-triggered
  - entity: automation.dimmer_off_while_off
    secondary_info: last-triggered
  - entity: automation.dimmer_up_while_on
    secondary_info: last-triggered
  - entity: automation.dimmer_down_while_on
    secondary_info: last-triggered
- type: entities
  title: House
  show_header_toggle: false
  entities:
  - entity: automation.house_mode_auto
    secondary_info: last-triggered
  - entity: automation.house_mode_away
    secondary_info: last-triggered
  - entity: automation.house_mode_bedtime
    secondary_info: last-triggered
  - entity: automation.house_mode_holiday
    secondary_info: last-triggered
- type: entities
  title: Hall
  show_header_toggle: false
  entities:
  - entity: automation.hall_lights_to_away
    secondary_info: last-triggered
  - entity: automation.hall_lights_to_bedtime
    secondary_info: last-triggered
  - entity: automation.hall_lights_to_dim
    secondary_info: last-triggered
  - entity: automation.hall_lights_to_night_on
    secondary_info: last-triggered
  - entity: automation.hall_lights_to_off
    secondary_info: last-triggered
  - type: divider
  - entity: automation.hall_mode_away
    secondary_info: last-triggered
  - entity: automation.hall_mode_bedtime
    secondary_info: last-triggered
  - entity: automation.hall_mode_bedtime_reset
    secondary_info: last-triggered
  - entity: automation.hall_mode_dim
    secondary_info: last-triggered
  - entity: automation.hall_mode_night_on
    secondary_info: last-triggered
  - entity: automation.hall_mode_off
    secondary_info: last-triggered
  - type: divider
  - entity: automation.hall_lights_unavailable_off
    secondary_info: last-triggered
- type: entities
  title: Vestibule
  show_header_toggle: false
  entities:
  - entity: automation.vestibule_lights_to_away
    secondary_info: last-triggered
  - entity: automation.vestibule_lights_to_bedtime
    secondary_info: last-triggered
  - entity: automation.vestibule_lights_to_off
    secondary_info: last-triggered
  - entity: automation.vestibule_lights_to_on
    secondary_info: last-triggered
  - entity: automation.vestibule_lights_to_night_on
    secondary_info: last-triggered
  - type: divider
  - entity: automation.vestibule_mode_away
    secondary_info: last-triggered
  - entity: automation.vestibule_mode_bedtime
    secondary_info: last-triggered
  - entity: automation.vestibule_mode_off
    secondary_info: last-triggered
  - entity: automation.vestibule_mode_on
    secondary_info: last-triggered
  - entity: automation.vestibule_mode_night_on
    secondary_info: last-triggered
- type: entities
  title: Family room
  show_header_toggle: false
  entities:
  - entity: automation.family_room_occupied
    secondary_info: last-triggered
  - entity: automation.family_room_not_occupied
    secondary_info: last-triggered
  - type: divider
  - entity: automation.family_room_arrival
    secondary_info: last-triggered
  - entity: automation.family_room_mode_away
    secondary_info: last-triggered
  - entity: automation.family_room_mode_bedtime
    secondary_info: last-triggered
  - entity: automation.family_room_mode_off
    secondary_info: last-triggered
  - entity: automation.family_room_mode_on
    secondary_info: last-triggered
  - type: divider
  - entity: automation.family_room_lights_to_away
    secondary_info: last-triggered
  - entity: automation.family_room_lights_to_bedtime
    secondary_info: last-triggered
  - entity: automation.family_room_lights_to_off
    secondary_info: last-triggered
  - entity: automation.family_room_lights_to_on
    secondary_info: last-triggered
- type: entities
  title: Front of the house
  show_header_toggle: false
  entities:
  - entity: automation.number_on_at_sunset
    secondary_info: last-triggered
  - entity: automation.number_on_in_the_morning
    secondary_info: last-triggered
  - entity: automation.number_sign_off
    secondary_info: last-triggered
  - entity: automation.person2_up_early
    secondary_info: last-triggered
  - entity: automation.returned_home
    secondary_info: last-triggered
  - entity: automation.front_door_open
    secondary_info: last-triggered
  - entity: automation.front_door_closed
    secondary_info: last-triggered
  - entity: automation.garage_door_open
    secondary_info: last-triggered
  - entity: automation.garage_door_closed
    secondary_info: last-triggered
  - entity: automation.garage_open_nobody_home
    secondary_info: last-triggered
  - entity: automation.person2_away_garage_open
    secondary_info: last-triggered
  - entity: automation.probably_leaving
    secondary_info: last-triggered
- type: entities
  title: Garden
  show_header_toggle: false
  entities:
  - entity: automation.utility_door_open_after_sunset_closed
    secondary_info: last-triggered
  - entity: automation.utility_door_open_after_sunset_turn_on
    secondary_info: last-triggered
  - entity: automation.utility_door_open_after_sunset_turn_off
    secondary_info: last-triggered
  - entity: automation.nighttime_garden_off
    secondary_info: last-triggered
  - entity: automation.garden_lights_left_on
    secondary_info: last-triggered
  - entity: automation.utility_door_left_open
    secondary_info: last-triggered
  - entity: binary_sensor.garden_lights_left_on
    secondary_info: last-changed
- type: entities
  title: Automations for the office
  show_header_toggle: false
  entities:
  - entity: automation.play_music_in_the_office
    secondary_info: last-triggered
  - entity: automation.pause_music_in_the_office
    secondary_info: last-triggered
  - entity: automation.resume_music_in_the_office
    secondary_info: last-triggered
  - type: divider
  - entity: automation.office_occupied
    secondary_info: last-triggered
  - entity: automation.office_not_occupied
    secondary_info: last-triggered
  - entity: automation.office_button_pushed
    secondary_info: last-triggered
  - type: divider
  - entity: automation.hotter_outside_office
    secondary_info: last-triggered
